name: Build and Push Docker

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      latest_version: '3.12'
    strategy:
      matrix:
        python-version: ["3.10", "3.11", '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set environment variables
      run: |
        echo "LOWER_CASE_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        echo "LOWER_CASE_REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV

    - name: Get remote old image digest
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        REMOTE_DIGEST=$(docker manifest inspect ghcr.io/temp-${{ env.LOWER_CASE_REPOSITORY }}:${{ matrix.python-version }} --verbose | jq -r '.Descriptor.digest')
        echo "OLD_REMOTE_DIGEST=$REMOTE_DIGEST" >> $GITHUB_ENV
        echo "Remote old image digest: $OLD_REMOTE_DIGEST"

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        provenance: false
        tags: ghcr.io/temp-${{ env.LOWER_CASE_REPOSITORY }}:${{ matrix.python-version }}
        build-args: |
          PYTHON_VERSION=${{ matrix.python-version }}

    - name: Get remote old image digest
      run: |
        sleep 10
        export DOCKER_CLI_EXPERIMENTAL=enabled
        REMOTE_DIGEST=$(docker manifest inspect ghcr.io/temp-${{ env.LOWER_CASE_REPOSITORY }}:${{ matrix.python-version }} --verbose | jq -r '.Descriptor.digest')
        echo "NEW_REMOTE_DIGEST=$REMOTE_DIGEST" >> $GITHUB_ENV
        echo "Remote new image digest: $NEW_REMOTE_DIGEST"

    - name: Push image if digests are different
      if: env.OLD_REMOTE_DIGEST != env.NEW_REMOTE_DIGEST
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        provenance: false
        tags: |
          charahiro/${{ env.REPOSITORY_NAME }}:${{ matrix.python-version }}
          ghcr.io/${{ env.LOWER_CASE_REPOSITORY }}:${{ matrix.python-version }}
          ${{ matrix.python-version == env.latest_version && format('charahiro/{0}:latest', env.REPOSITORY_NAME) || '' }}
          ${{ matrix.python-version == env.latest_version && format('ghcr.io/{0}:latest', env.LOWER_CASE_REPOSITORY) || '' }}
        build-args: |
          PYTHON_VERSION=${{ matrix.python-version }}