name: Build and Push Docker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      latest_version: '3.12'
    strategy:
      matrix:
        python-version: ["3.10", "3.11", '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          charahiro/steamcmd-python:${{ matrix.python-version }}
          ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${GITHUB_REPOSITORY,,}:${{ matrix.python-version }}
          ${{ matrix.python-version == env.latest_version && 'charahiro/steamcmd-python:latest' || '' }}
          ${{ matrix.python-version == env.latest_version && 'ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${GITHUB_REPOSITORY,,}:latest' || '' }}
        build-args: |
          PYTHON_VERSION=${{ matrix.python-version }}