name: Build and Push Docker

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      latest_version: '3.12'
    strategy:
      matrix:
        python-version: ["3.10", "3.11", '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set environment variables
      run: |
        echo "LOWER_CASE_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        echo "LOWER_CASE_REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        load: true
        tags: charahiro/${{ env.REPOSITORY_NAME }}:${{ matrix.python-version }}
        build-args: |
          PYTHON_VERSION=${{ matrix.python-version }}
        platforms: linux/amd64,linux/arm64

    - name: Get local image digest
      id: localdigest
      run: echo "::set-output name=digest::$(docker inspect --format='{{.RepoDigests}}' charahiro/${{ env.REPOSITORY_NAME }}:${{ matrix.python-version }})"

    - name: Get remote image digest
      id: remotedigest
      run: |
        DIGEST=$(docker pull charahiro/${{ env.REPOSITORY_NAME }}:${{ matrix.python-version }} || true)
        echo "::set-output name=digest::$(echo $DIGEST | grep 'Digest:' | awk '{print $2}')"

    - name: Push image if digests are different
      if: steps.localdigest.outputs.digest != steps.remotedigest.outputs.digest
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          charahiro/${{ env.REPOSITORY_NAME }}:${{ matrix.python-version }}
          ghcr.io/${{ env.LOWER_CASE_REPOSITORY }}/${{ env.REPOSITORY_NAME }}:${{ matrix.python-version }}
          ${{ matrix.python-version == env.latest_version && format('charahiro/{0}:latest', env.REPOSITORY_NAME) || '' }}
          ${{ matrix.python-version == env.latest_version && format('ghcr.io/{0}/{1}:latest', env.LOWER_CASE_REPOSITORY, env.REPOSITORY_NAME) || '' }}
        build-args: |
          PYTHON_VERSION=${{ matrix.python-version }}
        platforms: linux/amd64,linux/arm64